/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;



import javax.swing.*;
import java.awt.Image;
import java.awt.GridLayout;
import java.net.URL;
import java.util.List;
import model.Game;
import model.GameLibrary;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Color;


/**
 *
 * @author Muhammad syifaaul
 */
public class ExploreFrame extends javax.swing.JFrame {
    private DefaultListModel<ImageIcon> listModel;
    private GameLibrary gameStore;
    private List<Game> games; 


    public ExploreFrame() {
         initComponents();
         JPanel jPanel1 = new JPanel();
        jPanel1.setBackground(new Color(0, 0, 0));
        gameStore = new GameLibrary();
        listModel = new DefaultListModel<>();
        jList1.setModel(listModel);
        jList1.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        jList1.setVisibleRowCount(-1);
        jList1.setLayout(new GridLayout(0, 4));

        jList1.addMouseListener(new MouseAdapter() {
    public void mouseClicked(MouseEvent evt) {
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 1) {
            int index = list.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Game selectedGame = games.get(index); 
                openDetailForm(selectedGame);
            }
        }
    }
});


        games = gameStore.getAllGames(); 
        displayResults(games);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();
        searchByCategory = new javax.swing.JButton();
        searchByName = new javax.swing.JButton();
        searchByPrice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));

        searchField.setBackground(new java.awt.Color(102, 102, 102));
        searchField.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        searchField.setForeground(new java.awt.Color(204, 204, 204));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchByCategory.setBackground(new java.awt.Color(102, 102, 102));
        searchByCategory.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        searchByCategory.setForeground(new java.awt.Color(204, 204, 204));
        searchByCategory.setText("Search By Category");
        searchByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByCategoryActionPerformed(evt);
            }
        });

        searchByName.setBackground(new java.awt.Color(102, 102, 102));
        searchByName.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        searchByName.setForeground(new java.awt.Color(204, 204, 204));
        searchByName.setText("Search By Name");
        searchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByNameActionPerformed(evt);
            }
        });

        searchByPrice.setBackground(new java.awt.Color(102, 102, 102));
        searchByPrice.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        searchByPrice.setForeground(new java.awt.Color(204, 204, 204));
        searchByPrice.setText("Search By Price");
        searchByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByPriceActionPerformed(evt);
            }
        });

        jList1.setBackground(new java.awt.Color(12, 121, 136));
        jList1.setBorder(null);
        jList1.setModel(new DefaultListModel<>()
        );
        jScrollPane1.setViewportView(jList1);

        jPanel1.setBackground(new java.awt.Color(12, 90, 110));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1316, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(374, 374, 374))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(searchByName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(searchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(searchByCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(168, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(231, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchByPrice)
                    .addComponent(searchByCategory)
                    .addComponent(searchByName))
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(196, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByCategoryActionPerformed

        String category = searchField.getText();
    games = gameStore.searchByCategory(category);  
    displayResults(games);
    }//GEN-LAST:event_searchByCategoryActionPerformed

    private void searchByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByPriceActionPerformed
        // TODO add your handling code here:
         try {
        int price = Integer.parseInt(searchField.getText());
        games = gameStore.searchByPrice(price);  
        displayResults(games);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid price.");
    }
    }//GEN-LAST:event_searchByPriceActionPerformed

    private void searchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByNameActionPerformed
        String name = searchField.getText();
    games = gameStore.searchByName(name);  
    displayResults(games);
    }//GEN-LAST:event_searchByNameActionPerformed
 
private void displayResults(List<Game> games) {
    listModel.clear();
    for (Game game : games) {
        ImageIcon icon = createImageIcon(game.getGambar());
        if (icon != null) {
            listModel.addElement(icon);
        }
    }
    if (listModel.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No games found.");
    }
}

    private ImageIcon createImageIcon(String imageUrl) {
        try {
            URL url = new URL(imageUrl);
            ImageIcon originalIcon = new ImageIcon(url);
        
     
            int width = 170;  
            int height = 120; 


            Image scaledImage = originalIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
            return new ImageIcon(scaledImage);
        } catch (Exception ex) {
            ex.printStackTrace();
            return null;
        }
    }

    private void openDetailForm(Game game) {
        
        DetailForm detailForm = new DetailForm();
        detailForm.setGameDetails(game);
        detailForm.setVisible(true);

    }



       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExploreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExploreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExploreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExploreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExploreFrame exploreFrame = new ExploreFrame();

            exploreFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<ImageIcon> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchByCategory;
    private javax.swing.JButton searchByName;
    private javax.swing.JButton searchByPrice;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
